version: '3.8'

services:
  eazimation_db:
    image: postgres:latest
    container_name: eazimation_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - eazimation_db:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    command: "/bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always

  api:
    build:
      args:
        port: ${PORT}
      dockerfile: api.dockerfile
    container_name: api
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    env_file:
      - .env
    restart: always

volumes:
  eazimation_db:
  redis: